hmcts/ccpay-bulkscanning-app

- README.md
- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/demo/controller/GetWelcomeTest.java
- src/main/java/uk/gov/hmcts/reform/demo/BulkScanningApiApplication.java
- src/main/java/uk/gov/hmcts/reform/demo/config/SwaggerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/demo/controller/BulkScanningController.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/PAY-2007?jql=sprint%20%3D%205303
Initial Project structure
```
[ ] Yes
[x] No
```
> Pay-2007 - Initial Project Structure

- src/integrationTest/java/uk/gov/hmcts/reform/bulkscanning/config/SwaggerPublisher.java
- src/integrationTest/java/uk/gov/hmcts/reform/bulkscanning/controller/GetWelcomeTest.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/BulkScanningApiApplication.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/config/SwaggerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/BulkScanningController.java
https://tools.hmcts.net/jira/browse/PAY-2007?jql=sprint%20%3D%205303
Renaming package names
```
[ ] Yes
[x] No
```
> PAY-2007 - Renaming Package names

- infrastructure/main.tf
- infrastructure/variables.tf
> fixed product name

- Jenkinsfile_CNP
- infrastructure/main.tf
- infrastructure/variables.tf
> demoMaster

- build.gradle
> Adding sonar dependency

- infrastructure/main.tf
PAY-1975
main.tf file corrected
```
[ ] Yes
[x ] No
```
> PAY-1975: main.tf file corrected

- charts/ccpay-bulkscanning-api/values.aat.template.yaml
- infrastructure/main.tf
> Aks migration from key vault

- infrastructure/main.tf
- infrastructure/output.tf
> enable db migration

- infrastructure/output.tf
> Adding output file

- infrastructure/output.tf
> removing property

- infrastructure/output.tf
> update dummy output

- src/main/resources/liquibase.properties
> liquibase property updated

- Jenkinsfile_CNP
> loading vault secrets

- Jenkinsfile_CNP
- charts/ccpay-bulkscanning-api/values.aat.template.yaml
> disabling liquibase to false

- charts/ccpay-bulkscanning-api/values.aat.template.yaml
> postgres changes

- infrastructure/main.tf
> postgres changes added spring data source url

- charts/ccpay-bulkscanning-api/values.aat.template.yaml
- src/main/resources/liquibase.properties
> Postgres db liquibase flag updated

- src/main/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceImpl.java
Pay- 2111
Search by CCD Issue fixed.
```
[ ] Yes
[x] No
```
> PAY-2111: Search by CCD Issue fixed.

- build.gradle
- config/pmd/ruleset.xml
- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentController.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/mapper/BulkScanPaymentRequestMapper.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/mapper/EnvelopeDtoMapper.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/mapper/PaymentDtoMapper.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/dto/PaymentDto.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/dto/ReportData.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/entity/EnvelopePayment.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/enums/EnvelopeSource.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/enums/ReportType.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/repository/PaymentRepository.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentService.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/utils/BulkScanningUtils.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/utils/DateUtil.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/utils/ExcelGeneratorUtil.java
- src/main/resources/db/changelog/db.changelog-0.1.yaml
- src/test/java/uk/gov/hmcts/reform/bulkscanning/functionaltest/PaymentControllerFunctionalTest.java
PAY-2059 : Ability to generate report for Data loss (payments that are missing data from Bulk Scan or Exela)
PAY-2061 : Ability to generate report for Unprocessed payments
PAY-2059 : Ability to generate report for Data loss (payments that are missing data from Bulk Scan or Exela)
PAY-2061 : Ability to generate report for Unprocessed payments
```
[ ] Yes
[X] No
```
> Pay 2061 reconciliation report

- src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentController.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/functionaltest/PaymentControllerFunctionalTest.java
PAY - 2061
PAY - 2059
Report Changes
```
[ ] Yes
[X] No
```
> PAY-2061: Ability to generate report for Unprocessed payments

- infrastructure/output.tf
PAY-2111: S2S Token Integration
PAY-2111: S2S Token Integration
```
[ ] Yes
[ ] No
```
> PAY-2111: S2S Token Integration

- Jenkinsfile_CNP
Updating jenkins file
```
[ ] Yes
[x] No
```
> Removing duplciated defenitions from jenkins file

- infrastructure/main.tf
- infrastructure/template/bulk-scanning-payment.json
API gateway configurtion
```
[ ] Yes
[x] No
```
> Updating to new way of implementing api gateway in tf files

- infrastructure/main.tf
Removing duplicates from main tf files
```
[ ] Yes
[x] No
```
> Removing duplicates from main tf files

- dependency-check-suppressions.xml
No ticket
Updating suppresssion file
```
[ ] Yes
[ x] No
```
> Adding new dependency check into suppression file

- infrastructure/main.tf
> removing duplciations from main tf file

- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/validator/BulkScanValidatorFunctionalTest.java
PAY-2111: Application YAML fix for AKS Deployment
PAY-2111: Application YAML fix for AKS Deployment
```
[ ] Yes
[X ] No
```
> PAY-2111: Application YAML fix for AKS Deployment

- src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentController.java
PAY-2111: Removed UserAuthorisation token from Bulkscan PUT API.
PAY-2111: Removed UserAuthorisation token from Bulkscan PUT API.
```
[ ] Yes
[X] No
```
> PAY-2111: Removed UserAuthorisation token from Bulkscan PUT API.

- src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentController.java
PAY-2111 : Authrisation removed from BS API. 
PAY-2111 : Authrisation removed from BS API. 
```
[ ] Yes
[X] No
```
> PAY-2111 : Authrisation removed from BS API. 

- src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentController.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/mapper/BulkScanPaymentRequestMapper.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/mapper/PaymentDtoMapper.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/dto/ReportDataDataLoss.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/dto/ReportDataUnprocessed.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/enums/EnvelopeSource.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPayment.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/response/SearchResponse.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/utils/BulkScanningUtils.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/functionaltest/PaymentControllerFnTest.java
Pay-2273: search processed payments
Pay-2273: search processed payments
```
[ ] Yes
[X] No
```
> Pay-2273: search processed payments

- dependency-check-suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/validator/BulkScanValidatorFunctionalTest.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/AuthCheckerServiceAndAnonymousUserFilter.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentController.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/mapper/BulkScanPaymentRequestMapper.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/mapper/PaymentMetadataDtoMapper.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPayment.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPaymentRequest.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/response/SearchResponse.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/functionaltest/PaymentControllerFnTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceTest.java
Pay 2273: search processed payments
Pay 2273: search processed payments
```
[ ] Yes
[ X] No
```
> Pay 2273 search processed payments

- src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentController.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentService.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/utils/BulkScanningUtils.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/functionaltest/PaymentControllerFnTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceTest.java
> BulkScanning Changes

- src/main/java/uk/gov/hmcts/reform/bulkscanning/audit/AppInsightsAuditRepository.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/audit/AuditRepository.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceTest.java
PAY-2268 : Revert - Configure App Insight.
PAY-2268 : Revert - Configure App Insight.
```
[ ] Yes
[X] No
```
> PAY-2268 : Revert - Configure App Insight.

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerFunctionalTest.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentController.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/mapper/PaymentMetadataDtoMapper.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPayment.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPaymentRequest.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/utils/DateUtil.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/functionaltest/PaymentControllerFnTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceTest.java
Pay-1995: metadata validation
Pay-1995: metadata validation
```
[ ] Yes
[ X] No
```
> Pay-1995: metadata validation

- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPayment.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPaymentRequest.java
PAY-1995: Validation error message wording changes.
PAY-1995: Validation error message wording changes.
```
[ ] Yes
[ x] No
```
> PAY-1995: Validation error message wording changes.

- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPayment.java
PAY-1995: Validation message change
PAY-1995: Validation message change
```
[ ] Yes
[ x] No
```
> PAY-1995: Validation message change

- charts/ccpay-bulkscanning-api/Chart.yaml
- charts/ccpay-bulkscanning-api/values.yaml
> Updating image name and charts version

- charts/ccpay-bulkscanning-api/requirements.yaml
Updating java version
```
[ ] Yes
[ ] No
```
> Updating java version

- dependency-check-suppressions.xml
Adding new supperssion
```
[ ] Yes
[ ] No
```
> Adding new supperssion

- Jenkinsfile_CNP
- charts/ccpay-bulkscanning-api/Chart.yaml
- charts/ccpay-bulkscanning-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/PAY-2612
Updating some files for helm upgrade
```
[ ] Yes
[x] No
```
> Updating some files for helm upgrade

- .travis.yml
- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/validator/BulkScanValidatorFunctionalTest.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/validator/BulkScanControllerValidator.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/BulkScanningApiApplicationTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/backdoors/UserResolverBackdoor.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/functionaltest/PaymentControllerFnTest.java
Response Logger Added
Response Logger Added
```
[ ] Yes
[X ] No
```
> Merge to master

- Jenkinsfile_CNP
- charts/ccpay-bulkscanning-api/Chart.yaml
- charts/ccpay-bulkscanning-api/requirements.yaml
- charts/ccpay-bulkscanning-api/values.aat.template.yaml
- charts/ccpay-bulkscanning-api/values.preview.template.yaml
- charts/ccpay-bulkscanning-api/values.yaml
- dependency-check-suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerFunctionalTest.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPayment.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPaymentRequest.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/SearchRequest.java
- src/main/resources/bootstrap.yaml
- src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/SearchControllerTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/functionaltest/PaymentControllerFnTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/validator/BulkScanValidatorTest.java
Dcn length validation
Dcn length validation
```
[ ] Yes
[ x] No
```
> Dcn length validation

- dependency-check-suppressions.xml
PAY-2639 : CVE suppressed
PAY-2639 : CVE suppressed
```
[ ] Yes
[ x] No
```
> PAY-2639 : CVE suppressed

- config/owasp/suppressions.xml
PAY-2639 : NEW CVEs Suppressed.
PAY-2639 : NEW CVEs Suppressed.
```
[ ] Yes
[x ] No
```
> PAY-2639 : NEW CVEs Suppressed.

- Jenkinsfile_nightly
- audit.json
- build.gradle
- dependency-check-suppressions.xml
- security.sh
Mutation testing changes
Mutation testing changes
```
[ ] Yes
[ x] No
```
> Mutation testing changes

- .travis.yml
- build.gradle
- config/pmd/ruleset.xml
- src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/AuthCheckerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentController.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/ReportController.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/SearchController.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/dto/BaseReportData.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/dto/ReportDataDataLoss.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/dto/ReportDataUnprocessed.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/service/ReportService.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/service/ReportServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/service/SearchServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/utils/BulkScanningUtils.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/utils/DateUtil.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/utils/ExcelGeneratorUtil.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/ReportControllerTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/service/PaymentServiceTest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/utils/BulkScanningUtilsTest.java
PAY-2639 : Sonar Configuration
PAY-2639 : Sonar Configuration
```
[ ] Yes
[x ] No
```
> PAY-2639 : Sonar Configuration

- src/main/java/uk/gov/hmcts/reform/bulkscanning/service/ReportServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerTest.java
Sonar analysis bug fix
Sonar analysis bug fix
```
[ ] Yes
[ x] No
```
> Sonar analysis bug fix

- Jenkinsfile_CNP
- audit.json
> PAY-2870-Low priority security scan issue suppress for nightlyBuild

- dependency-check-suppressions.xml
> PAY-2870:Suppressing CVE for timebeing

- build.gradle
- config/owasp/suppressions.xml
> PAY-2953:Upgraded Spring boots Starter Version

- Jenkinsfile_CNP
AB#848
Switch to AKS on AAT
```
[ ] Yes
[x] No
```
> Switch to AKS on AAT

- Jenkinsfile_CNP
AB#848
Go live to AKS 
```
[ ] Yes
[x] No
```
> Switched prod to AKS

- charts/ccpay-bulkscanning-api/Chart.yaml
- charts/ccpay-bulkscanning-api/values.yaml
- src/main/resources/bootstrap.yaml
Added required secrets and updated chart version
> PAY-3156: Publish new product chart

- config/owasp/suppressions.xml
- infrastructure/perftest.tfvars
Add Krishna thumbprint into perftest.tfvars
https://tools.hmcts.net/jira/browse/PAY-2921
crating a new tf file and adding Krishna thumbprint into it
```
[ ] Yes
[x] No
```
> Add Krishna thumbprint into perftest.tfvars

- config/owasp/suppressions.xml
- infrastructure/perftest.tfvars
Adding Krishna's thumbprint into perftest 
https://tools.hmcts.net/jira/browse/PAY-2921
Adding Krishna's thumbprint into perftest 
```
[ ] Yes
[x] No
```
> Add thumbprint

- charts/ccpay-bulkscanning-api/Chart.yaml
- charts/ccpay-bulkscanning-api/values.yaml
> Added ccd gateway as audience

- config/owasp/suppressions.xml
> PAY-3317 - Nightly build suppression

- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/validator/BulkScanValidatorFunctionalTest.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/enums/ResponsibleSiteId.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPaymentRequest.java
> Pay 3167 b

- config/owasp/suppressions.xml
> PAY-3485 : Nightly Build Issue Fix

- build.gradle
- config/owasp/suppressions.xml
> PAY-3307 : Bulk scan CVE's Fix

- config/owasp/suppressions.xml
> supression added for tomcat-embed-core

- config/owasp/suppressions.xml
> CVE-2020-15250 supression added

- config/owasp/suppressions.xml
- docker-compose.yml
> Pay 3812 idam integration

- build.gradle
> fix added for guava

- infrastructure/main.tf
> PAY-3919 : Removed the OLD DB instance mapping from main.tf

- config/owasp/suppressions.xml
> Pay 3960 bulkscan suppression limit extend

- config/owasp/suppressions.xml
> PAY-4085: Nightly Build issue fix

- audit.json
> PAY-4115 : Nightly Build issue Fix

- config/owasp/suppressions.xml
> PAY-4179 : Nightly build issue fix

- audit.json
> timestamp disclosure added

- config/owasp/suppressions.xml
- cve-resolution-strategy.gradle
> removed the supression and added the fix

- build.gradle
> jitpack and liquibase new version added

- build.gradle
- cve-resolution-strategy.gradle
> Cve 2021 29425 fix

- charts/ccpay-bulkscanning-api/Chart.yaml
- cve-resolution-strategy.gradle
> Chart version upgraded to 3.4.5

- Dockerfile
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerFunctionalTest.java
> Nightly Build issue Fix

- audit.json
> added the finger prints - nightly build failure

- audit.json
> audit.json refactored

- Jenkinsfile_CNP
> to keep-environment-specific-branches-in-sync-with-master

- security.sh
> Nightly fix for security scan

- cve-resolution-strategy.gradle
> nightly fix check

- cve-resolution-strategy.gradle
- src/smokeTest/java/uk/gov/hmcts/reform/bulkscanning/smoke/SmokeTest.java
> Night fix compress jar

- audit.json
- config/owasp/suppressions.xml
- cve-resolution-strategy.gradle
> Nightly dev

- Jenkinsfile_CNP
- build.gradle
- charts/ccpay-bulkscanning-api/Chart.yaml
- config/fortify-client.properties
- cve-resolution-strategy.gradle
> Pay 4971 fortify changes

- Jenkinsfile_CNP
- build.gradle
- config/fortify-client.properties
> added fortify configuration changes

- config/owasp/suppressions.xml
- infrastructure/state.tf
> terraform issue fix

- cve-resolution-strategy.gradle
> CVE FIX : CVE-2021-22096

- config/owasp/suppressions.xml
> build issue fix

- build.gradle
> log4j upgrade

- build.gradle
> log4j upgrade to 2.16.0

- config/fortify-client.properties
> new fortify release id

- build.gradle
- src/main/java/uk/gov/hmcts/reform/bulkscanning/config/security/filiters/ServiceAndUserAuthFilter.java
> PAY-5279 Fortify Suppression and log4j version upgrade

- cve-resolution-strategy.gradle
> cve fixes 14 feb 2022

- Jenkinsfile_nightly
- build.gradle
- config/owasp/suppressions.xml
> CVE issue nightly build

- config/owasp/suppressions.xml
> Suppressed CVE - CVE-2022-22950.

- config/owasp/suppressions.xml
> Suppressed CVE - CVE-2016-1000027.

- config/owasp/suppressions.xml
- security.sh
> Suppressed CVE - CVE-2022-22968.

- cve-resolution-strategy.gradle
> CVE Fix - CVE-2022-29885.

- Jenkinsfile_nightly
- config/owasp/suppressions.xml
> Extend cve date to 30/09/2022 and disable night job for nightly branch.

- charts/ccpay-bulkscanning-api/Chart.yaml
- config/owasp/suppressions.xml
> fix for CVE-2022-34305

- charts/ccpay-bulkscanning-api/Chart.yaml
- charts/ccpay-bulkscanning-api/values.preview.template.yaml
> PAY-5683 Java version upgrade in chart yaml

- src/main/resources/application-local.yaml
> Fix fortify scan issue for username

- config/owasp/suppressions.xml
> Suppressed - CVE-2022-42004, CVE-2022-42003

- audit.json
> Added new fingerprint for security scan

- cve-resolution-strategy.gradle
> Update tomcat embed version

- config/owasp/suppressions.xml
> supressing cve issue with no fix

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- charts/ccpay-bulkscanning-api/Chart.yaml
> updated deprecated after to afterAlways

- config/owasp/suppressions.xml
> fixing cve

- charts/ccpay-bulkscanning-api/Chart.yaml
- config/owasp/suppressions.xml
> suppress cve

- config/owasp/suppressions.xml
> suppressing new cve

- audit.json
> JSON Surpression

- src/main/java/uk/gov/hmcts/reform/bulkscanning/controller/SearchController.java
- src/main/resources/application.yaml
> removal of logging statements

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-4884
Suppression for CVE with no fix available.
```
[ ] Yes
[x] No
```
> Suppression for cve with no fix available.

- charts/ccpay-bulkscanning-api/Chart.yaml
- charts/ccpay-bulkscanning-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/PAY-5997
Updating to support new private dns entry.
```
[ ] Yes
[x] No
```
> PAY-5997: Updating to support new private dns entry.

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-6040
Suppress CVE as no fix is available.
```
[ ] Yes
[x] No
```
> Update to fix CVEs

- Jenkinsfile_CNP
- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/PAY-6400
Update slack mapping to fee-pay-nightly-pipeline.
```
[ ] Yes
[x] No
```
> PAY-6400: Update new slack mapping

- .github/workflows/ci.yml
- Dockerfile
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- lib/applicationinsights.json
PAY-6021: Pre-Requisite: Upgrade Spring Boot & App Insights
[PAY-6021] (https://tools.hmcts.net/jira/browse/PAY-6021).
> PAY-6021: Pre-Requisite: Upgrade Spring Boot & App Insights

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-6443
Added CVE fixe, but doesn't appear to work, so had to suppress anyway.
```
[ ] Yes
[x] No
```
> PAY-6443: Add CVE resolution fix and suppression

- config/owasp/suppressions.xml
PAY-6516:  CVES
[PAY-6516] (https://tools.hmcts.net/jira/browse/PAY-6516).
> PAY-6516:  CVES

- .github/renovate.json
PAY-6544: Renovate
[PAY-6544] (https://tools.hmcts.net/jira/browse/PAY-6544).
> PAY-6544: Renovate

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PAY-6572
Addtiona flexibl DB server added to main.ft file
```
[ ] Yes
[X] No
```
> PAY-6572_Postgres-Migration for Demo

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PAY-6572
```
[ ] Yes
[X] No
```
> PAY-6572_Postgres-Migration v15 for Demo

- infrastructure/main.tf
PAY-6572
```
[ ] Yes
[X] No
```
> PAY-6572_Postgres-Migration v15 for Demo removed public_access=true

- config/owasp/suppressions.xml
- infrastructure/main.tf
- infrastructure/provider.tf
- infrastructure/state.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PAY-6572
Merge demo update into master for flexible server creation
```
[ ] Yes
[X] No
```
> Pay 6572 postgres migration

- charts/ccpay-bulkscanning-api/Chart.yaml
- config/owasp/suppressions.xml
- infrastructure/main.tf
[PAY-6572](https://tools.hmcts.net/jira/browse/PAY-6572)
Amended the flexible server extentions
```
[ ] Yes
[X] No
```
> PAY-6572 amend extensions for flexible

- Dockerfile
https://tools.hmcts.net/jira/browse/PAY-6608
Added a version as suggested by fortify
```
[ ] Yes
[X ] No
```
> add version as suggested by fortify scan PAY-6608

- charts/ccpay-bulkscanning-api/Chart.yaml
- charts/ccpay-bulkscanning-api/values.yaml
PAY-6572
amend yaml file for secrets
```
[ ] Yes
[x] No
```
> PAY-6572 amend yaml file

- infrastructure/sdp.tf
https://tools.hmcts.net/jira/browse/PAY-6681
SDP user setup in new flexible server db
```
[ ] Yes
[x] No
```
> PAY-6681 setup of SDP user

- charts/ccpay-bulkscanning-api/Chart.yaml
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PAY-6701
Force access to flexible server db
```
[ ] Yes
[X] No
```
> PAY-6701 Force Access to flexible db

- infrastructure/sdp.tf
https://tools.hmcts.net/jira/browse/PAY-6702
SDP user access amended
```
[ ] Yes
[X] No
```
> PAY-6702 SDP user access

- build.gradle
- config/owasp/suppressions.xml
- infrastructure/main.tf
- infrastructure/sdp.tf
https://tools.hmcts.net/jira/browse/PAY-6717
Added some missing secrets, fixed a logstash issue, added some suppressions for CVEs which will be address during the next springboot update.
```
[ ] Yes
[x] No
```
> PAY-6717: Update secrets to point to v15 and add/fix suppressions.

- build.gradle
- cve-resolution-strategy.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/config/BulkScanPaymentTestService.java
- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/config/IdamApi.java
- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/config/IdamService.java
- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/controller/PaymentControllerFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/validator/BulkScanValidatorFunctionalTest.java
https://tools.hmcts.net/jira/browse/PAY-6599
```
[ ] Yes
[X] No
```
> Pay 6599 refactor and improve FTs coverage

- charts/ccpay-bulkscanning-api/Chart.yaml
- charts/ccpay-bulkscanning-api/values.yaml
- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PAY-6659
Decommission v11 bulkscan database
```
[ ] Yes
[x] No
```
> PAY-6659 Decommission v11 database

- README.md
PAY-6838v8
Pull master into nightly dev
```
[ ] Yes
[ x ] No
```
> PAY-6838v8

- README.md
PAY_6838
Pull master into nightly dev
```
[ ] Yes
[ x ] No
```
> PAY_6838v0

- src/main/resources/application-local.yaml
https://tools.hmcts.net/jira/browse/PAY-6855
remove hard coded password
```
[ ] Yes
[X] No
```
> PAY-6885 remove hardcoded password, which causes Fortify Scan failure

- cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-6887
Addressed CVE-2023-34042
```
[ ] Yes
[x] No
```
> PAY-6887- CVE 2023-34042 addressed

- config/owasp/suppressions.xml
PAY-6911: Pipeline analysis and resolution 26 February 2023
[PAY-6911] (https://tools.hmcts.net/jira/browse/PAY-6911).
> PAY-6911: Pipeline analysis and resolution 26 February 2023

- cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-6972
Address CVE issue
```
[ ] Yes
[X] No
```
> PAY-6972_CVE-2024-26308 addressed.

- cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-6974
postgresql upgrade to address vulnerability https://nvd.nist.gov/vuln/detail/CVE-2024-1597
```
[ ] Yes
[X] No
```
> Pay 6974 pipeline fix

- build.gradle
- charts/ccpay-bulkscanning-api/Chart.yaml
- cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-6974
Update json-smart
```
[ ] Yes
[x] No
```
> PAY-6974: Update json-smart to non vulnerable version

- build.gradle
- config/owasp/suppressions.xml
- cve-resolution-strategy.gradle
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/PAY-7124
Address High Vulnerabilities
```
[ ] Yes
[x] No
```
> PAY-7124: Address High Vulnerabilities

- build.gradle
- config/owasp/suppressions.xml
- cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-7141
Fix to Medium CVE vulnerabilities.
```
[ ] Yes
[x] No
```
> PAY-7141: Address Medium Vulnerabilities

- infrastructure/cft-api-mgmt-subscriptions.tf
- infrastructure/cft-api-mgmt.tf
- infrastructure/provider.tf
https://tools.hmcts.net/jira/browse/PAY-6705
Change to set correct provider for new APIM
```
[ ] Yes
[x] No
```
> PAY-6602: Tidy up implementation.

- infrastructure/cft-api-mgmt.tf
- infrastructure/provider.tf
https://tools.hmcts.net/jira/browse/PAY-6705
Update to add bulk scanning payment api to new CFT APIM Mgmt Service.
```
[ ] Yes
[x] No
```
> PAY-6602 cft apim final

- infrastructure/cft-api-mgmt.tf
- infrastructure/template/cft-api-policy.xml
https://tools.hmcts.net/jira/browse/PAY-6602
Update API policy so it's different for new APIM.
```
[ ] Yes
[x] No
```
> PAY-6602: Update api-policy

- infrastructure/cft-api-mgmt.tf
- infrastructure/template/cft-api-policy.xml
https://tools.hmcts.net/jira/browse/PAY-6602
Fix APIM CFT Policy Errors
```
[ ] Yes
[x] No
```
> PAY-6602: Fix APIM CFT Policy Errors

- build.gradle
https://tools.hmcts.net/jira/browse/PAY-7212
Removed properties-volume-spring-boot-starter
```
[ ] Yes
[x] No
```
> PAY-7212: Remove properties-volume-spring-boot-starter

- build.gradle
https://tools.hmcts.net/jira/browse/PAY-7303
Upgrade IdAM Java client.
```
[ ] Yes
[x] No
```
> Upgrade IdAM Java Client - Pipeline fix

- .gitignore
- Dockerfile
- build.gradle
- src/test/java/uk/gov/hmcts/reform/bulkscanning/config/security/AuthCheckerConfigurationTest.java
- web.config
https://tools.hmcts.net/jira/browse/CME-63
```
[ ] Yes
[ ] No
```
> CME-63: Java 21

- .github/workflows/ci.yml
- docker-compose.yml
- src/functionalTest/java/uk/gov/hmcts/reform/bulkscanning/validator/BulkScanValidatorFunctionalTest.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/enums/ResponsibleSiteId.java
- src/main/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPaymentRequest.java
- src/test/java/uk/gov/hmcts/reform/bulkscanning/model/request/BulkScanPaymentRequestTest.java
- src/test/resources/application.yaml
https://tools.hmcts.net/jira/browse/PAY-7639
White lists PRL Resp Service ID - ABA5.
```
[ ] Yes
[x] No
```
> PAY-7639: Whitelist PRL Resp Service ID

- charts/ccpay-bulkscanning-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CME-422
```
[ ] Yes
[ ] No
```
> CME-422: OCI image

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PAY-7766
removal of azure extension in the main.tf file.
```
[ ] Yes
[x] No
```
> PAY-7766 removal of azure extension

- infrastructure/main.tf
- infrastructure/variables.tf
Reverts hmcts/ccpay-bulkscanning-app#586
> Revert "Cme 126 testing db monitoring"

- Jenkinsfile_CNP
- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-126
Added action group to alert about high database usage.
```
[ ] Yes
[x] No
```
> CME-126 add db monitoring action group

- infrastructure/cft-api-mgmt.tf
- infrastructure/template/cft-api-policy-oauth2.xml
- infrastructure/template/cft-api-policy.xml
https://tools.hmcts.net/jira/browse/PAY-7886
Testing Plan is correct after update.
```
[ ] Yes
[x] No
```
> PAY-7850: Change to invoke update

- charts/ccpay-bulkscanning-api/Chart.yaml
- charts/ccpay-bulkscanning-api/values.yaml
- infrastructure/cft-api-mgmt-oauth2.tf
- infrastructure/cft-api-mgmt.tf
- infrastructure/template/cft-api-policy-oauth2.xml
- infrastructure/template/cft-api-policy.xml
https://tools.hmcts.net/jira/browse/PAY-7850
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> PAY-7850: Update S2S Gateway Secret
